/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
Traceback (most recent call last):
  File "/content/drive/MyDrive/HiCMAE/run_class_finetuning_av.py", line 730, in <module>
    main(opts, ds_init)
  File "/content/drive/MyDrive/HiCMAE/run_class_finetuning_av.py", line 231, in main
    utils.init_distributed_mode(args)
  File "/content/drive/MyDrive/HiCMAE/utils.py", line 282, in init_distributed_mode
    torch.cuda.set_device(args.gpu)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 313, in set_device
    torch._C._cuda_setDevice(device)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 216, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Traceback (most recent call last):
  File "/content/drive/MyDrive/HiCMAE/run_class_finetuning_av.py", line 730, in <module>
    main(opts, ds_init)
  File "/content/drive/MyDrive/HiCMAE/run_class_finetuning_av.py", line 231, in main
    utils.init_distributed_mode(args)
  File "/content/drive/MyDrive/HiCMAE/utils.py", line 282, in init_distributed_mode
    torch.cuda.set_device(args.gpu)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 313, in set_device
    torch._C._cuda_setDevice(device)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 216, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Traceback (most recent call last):
  File "/content/drive/MyDrive/HiCMAE/run_class_finetuning_av.py", line 730, in <module>
    main(opts, ds_init)
  File "/content/drive/MyDrive/HiCMAE/run_class_finetuning_av.py", line 231, in main
    utils.init_distributed_mode(args)
  File "/content/drive/MyDrive/HiCMAE/utils.py", line 282, in init_distributed_mode
    torch.cuda.set_device(args.gpu)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 313, in set_device
    torch._C._cuda_setDevice(device)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 216, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Traceback (most recent call last):
  File "/content/drive/MyDrive/HiCMAE/run_class_finetuning_av.py", line 730, in <module>
    main(opts, ds_init)
  File "/content/drive/MyDrive/HiCMAE/run_class_finetuning_av.py", line 231, in main
    utils.init_distributed_mode(args)
  File "/content/drive/MyDrive/HiCMAE/utils.py", line 282, in init_distributed_mode
    torch.cuda.set_device(args.gpu)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 313, in set_device
    torch._C._cuda_setDevice(device)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 216, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 38102) of binary: /usr/bin/python3
